### PR TITLE
travis -> DoCIF

### LINKED ISSUE #64: Make deployment similar on all platforms
Following some discussion in #61, it might be better if we factored out parts of the travis ci build script into a `install.sh`, so that 

```
git clone
./install.sh
```

would install system dependencies, run `setup.py`, install rosdeps, etc. and allow deployment to be done the same way across all systems.

### LINKED ISSUE #88: Consider having different travis builds for testing and linting
Using travis build matrix:
https://docs.travis-ci.com/user/speeding-up-the-build/
https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix

### LINKED ISSUE #89: Freeze dependencies
https://github.com/gtagency/buzzmobile/blob/master/buzzmobile/setup.py#L11

We want to freeze the requirements as such:

http://www.kennethreitz.org/essays/a-better-pip-workflow

The idea is that we depend on a specific release of each of our dependencies, not on the latest release. When those dependencies get updated, they won't break our code.

We'd ideally freeze all our deps, not just python's. But idk how to easily do that with ROS dependencies.

### PR DESCRIPTION
**Pull request by irapha**
Changes the continuous integration tool used by our repo from travis ci to DoCIF, which uses circle-ci, docker, and virtualenv to allow us to have multiple tests and statused per build run.

Fixes #88 
Fixes #64 
Fixes #89
Part of #87 
Part of #51 (along with #86)

### CODE REVIEW

**Comment by joshuamorton** [comment]
Closes #88 
Starts on #87 
Closes #64 
Partially Addresses #51 
We can also address #89 in this PR as well, since it is already partially addressed.

**Comment by irapha** [comment]
I wouldn't say this PR has a fix for #87 just yet. That issue includes converting whatever python scripts that aren't py3 compliant into py3.

It's also not a fix for #51 until #86 is done and merged.

I'm in favor of fixing #89 here too. feel free to start. I'm gonna make slight modifications to README and squash commits really soon.

**Comment by irapha** [comment]
Sorry about the failed rebase+squash. We'll just squash through github.

This PR is waiting on freezing deps in `setup.py` and testing intallation on a fresh install VM. (plus running some nodes as a test). After that, we'll merge. But I'm marking it for review now if anyone has comments.

**Comment by joshuamorton** [comment]
closes #89

**Review by joshuamorton — APPROVED** [review]
As long as the install works in a clean VM, this looks good.

**Comment by irapha** [comment]
I just finished testing on a fresh VM. Going to merge it in now

**Pull request merged**
